name: BluHeli
options:
  bundleIdPrefix: es.moon.heli
  deploymentTarget:
    iOS: "15.0"
  createIntermediateGroups: true
targets:
  BluHeli:
    type: application
    platform: iOS
    sources:
      - Sources
    info:
      path: Info.plist
      properties:
        UISupportedExternalAccessoryProtocols:
          - com.silverlit.helicopter
          - com.silverlit.ferrari
          - com.silverlit.car
          - com.silverlit.airplane
          - com.silverlit.blueskyheli
          - com.silverlit.bsh
          - com.silverlit.bsh-a
          - com.silverlit.blutech
          - com.silverlit.blutechheli
          - com.silverlit.toy
          - com.silverlit.bt
          - com.silverlit.bluetooth
          - com.silverlit.heli
          - com.silverlit.control
          - com.silverlit.smartlink
          - com.silverlit.ia
          - com.silverlit.ferraribt
          - com.silverlit.rc
          - com.silverlit.protocol
          - com.silverlit.mfi
          - com.silverlit.enzo
          - com.silverlit.458
          - com.silverlit.speed
          - com.silverlit.bleferraricar
          - com.silverlit.btferrari
          - fi.wellmon.wECCAN
          - com.xpg.protocol
        UIBackgroundModes:
          - external-accessory
          - bluetooth-central
        NSBluetoothAlwaysUsageDescription: "BluHeli usa Bluetooth para conectar y controlar tu helicóptero Silverlit."
        NSBluetoothPeripheralUsageDescription: "BluHeli usa Bluetooth para comunicarse con accesorios MFi."
        UILaunchScreen: {}
        CODE_SIGNING_ALLOWED: "NO"
